### ISSUE TITLE
Jordan Rally

### ISSUE THREAD

**Issue by EvoBB** [crazyfacka/rally2gpx#17]
Hi, fantastic idea for the program. I wanted to start using but I have the following problem, where to find the solution?

`TypeError: Cannot read properties of undefined (reading 'length')
    at generateGPX (/home/pptruser/index.js:34:41)
    at /home/pptruser/index.js:130:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by crazyfacka** [comment]
Can you give me more details please? Which rally stage were you trying to download?

**Comment by EvoBB** [comment]
It was on every stage.

Now when im trying i have error. In the browser everything works fine, the rally page loads.
I would very much like to run your soft because it is very useful :)

`Downloading and parsing data from 'https://www.rally-maps.com/Forest-Rally-2024'
TimeoutError: Waiting for selector `.cm__body` failed: Waiting failed: 30000ms exceeded
    at new WaitTask (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:60:34)
    at IsolatedWorld.waitForFunction (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Realm.js:35:26)
    at PQueryHandler.waitFor (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/QueryHandler.js:180:95)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdpFrame.waitForSelector (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:504:21)
    at async CdpPage.waitForSelector (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:1324:20)
    at async scrapePage (/home/pptruser/index.js:85:3)`

**Comment by EvoBB** [comment]
`docker run --rm -it --init  -v d/data:/app/data crazyfacka/rally2gpx https://www.rally-maps.com/Rajd-Nadwi%C5%9Bla%C5%84ski-2024`
In my opinion, the error occurs when there are national characters in stage name. When you select stage with such characters in the name it does not ask for the file name but throws an error. In the example you gave with the iconic FAFE, when you select it, the system asks for the file name, if there are national characters then there is an error immediately after selection stage.

**Comment by crazyfacka** [comment]
I can load it successfully.

```
rally2gpx master * = $ node .\index.js https://www.rally-maps.com/Rajd-Nadwi%C5%9Bla%C5%84ski-2024
Downloading and parsing data from 'https://www.rally-maps.com/Rajd-Nadwi%C5%9Bla%C5%84ski-2024'
? What stage do you wish to generate the GPX (Use arrow keys)
> Shakedown (Płonki)
  SS 7+10 - Kurów
  Park Fermé (Puławy - Grupa Azoty Arena)
  Start/Finish/Podium (Puławy - Grupa Azoty Arena)
  SS 2+4 - Wilków
  SS 6+9 - Jastków
  Regrouping (Puławy - Grupa Azoty Arena)
(Move up and down to reveal more choices)
```

Now with a more attentive look, I reckon you're not running the docker as you should. In the README file there are more parameters to enable the opening of the Chromium browser.

**Comment by crazyfacka** [comment]
If possible, tell me the details of your system (locale included).

**Comment by crazyfacka** [comment]
No need. Something is weird with those Polish tracks, that it's not related with locale.
Will investigate further.

**Comment by crazyfacka** [comment]
Hey @EvoBB . When possible, either test the branch `handle_non_utf` or use the Docker image `crazyfacka/rally2gpx:dev`.
