### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by thatguyaknow** [crazyfacka/rally2gpx#8]
Hi,

I gotta imagine this isn't something that was meant to be maintained etc overtime but I was very interested in some .gpx files for a local rally so I gave it a whirl and am getting a timeout, I tried increasing it a few times but no dice.

`Downloading and parsing data from 'https://www.rally-maps.com/Sandblast-Rally-2022'
Error: Timed out waiting for resources
    at Timeout.<anonymous> (/app/index.js:34:16)
    at listOnTimeout (internal/timers.js:533:17)
    at processTimers (internal/timers.js:475:7)`

**Comment by PoorlyPlayingGod** [comment]
@crazyfacka would you plan on updating this?

**Comment by Hix-** [comment]
Getting the same timeout. 
`docker run --rm -it -v ./data:/app/data crazyfacka/rally2gpx https://www.rally-maps.com/Roger-Albert-Clark-Rally-2021
Downloading and parsing data from 'https://www.rally-maps.com/Roger-Albert-Clark-Rally-2021'
Error: Timed out waiting for resources
    at Timeout.<anonymous> (/app/index.js:34:16)
    at listOnTimeout (internal/timers.js:533:17)
    at processTimers (internal/timers.js:475:7)`

**Comment by crazyfacka** [comment]
Should be fixed now. It took some big rewriting in the logic given that the cookie dialogue employed some weird shenanigans.
